spring.application.name=engineeringhostel

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/engineering_hostel
spring.datasource.username=root
spring.datasource.password=Akash@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
